// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ClickStat struct {
	Code      string `json:"code"`
	Dimension string `json:"dimension"`
	Value     string `json:"value"`
	Count     int64  `json:"count"`
}

type Link struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	OriginalURL string             `json:"original_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
