// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (code, original_url)
VALUES ($1, $2)
RETURNING id, code, original_url, created_at
`

type CreateLinkParams struct {
	Code        string `json:"code"`
	OriginalURL string `json:"original_url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Code, arg.OriginalURL)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalURL,
		&i.CreatedAt,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, code, original_url, created_at FROM links WHERE code = $1
`

func (q *Queries) GetLink(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, code)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalURL,
		&i.CreatedAt,
	)
	return i, err
}
